version: "3"
services:
  node_dev_cloud:
    ports:
      - "9000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:root@mongo:27017/?authSource=admin

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: